apiVersion: v1
kind: Replicaset
metadata: 
  name: k8-service
spec:
  replicas: 3
  selector:
     matchLabels:
       kube: Task2
  template:
    metadata:
      labels:
        kube: Task2
    spec:         
  containers: 
  - name: ngnix
    image: ngnix
      