apiVersion: v1
kind: ReplicatonController
metadata:
  labels: 
    rs: ngnix
  name: nginx-test
spec: 
  containers:
  - name: nginx-test
    image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec: 
  selector:
    rs: nginx
  ports:
  - containerPort: 80