apiVersion: v1
kind: ReplicationController
metadata:
  labels: 
    rs: nginx
  name: nginx-test
spec:
  replicas: 3
  selector:
    rs: nginx
  template:
    metadata:
      labels:
        rs: nginx
    spec: 
      containers:
      - name: nginx-test
        image: nginx
        
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec: 
  selector:
    rs: nginx
  ports:
   - protocol: TCP
     port: 80
  type: NodePort   


     
