apiVersion: v1
kind: ReplicationController
metadata:
  labels: 
    rs: ngnix
  name: nginx-test
spec:
  replicas: 3
  selector:
     matchLabels:
       kube: Task2
  template:
    metadata:
      labels:
        kube: Task2
  spec: 
    containers:
    - name: nginx-test
      image: nginx
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec: 
  selector:
    rs: nginx
  ports:
   - protocol: TCP
     port: 80
